theme: jekyll-theme-minimal
title: koolthings | All KoOoOoL things you can think of!
description: All KoOoOoL things you can think of!
logo: /assets/macintosh-operating-systems-apple-happy-mac-computer-icons-png-favpng-kirRvzES8FP5LSyLjLqNSsdeS.jpg
show_downloads: true
